# -*- coding: utf-8 -*-
"""spam_email.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pRxznlKp2tnRpxBXFmkK8-wNEM_skfGV
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

raw_mail_data=pd.read_csv('/content/mail_data.csv')

print(raw_mail_data)

mail_data=raw_mail_data.where(((pd.notnull)(raw_mail_data)),'')

print(mail_data[:5])

mail_data.shape

mail_data.loc[mail_data['Category'] =='spam','Category',]=0
mail_data.loc[mail_data['Category'] =='ham','Category',]=1

X=mail_data['Message']
Y=mail_data['Category']

X

Y

X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2,random_state=3)

X.shape

X_train.shape

X_test.shape

feature_extraction=TfidfVectorizer(min_df=1, stop_words='english',lowercase=True)
X_train_features=feature_extraction.fit_transform(X_train)
x_test_features=feature_extraction.transform(X_test)
Y_train=Y_train.astype('int')
Y_test=Y_test.astype('int')

print(X_train_features)

model=LogisticRegression()

model.fit(X_train_features,Y_train)

prediction_on_training_data=model.predict(X_train_features)
accuracy_on_training_data=accuracy_score(Y_train,prediction_on_training_data)

print(accuracy_on_training_data)

prediction_on_test_data=model.predict(x_test_features)
accuracy_on_test_data=accuracy_score(Y_test,prediction_on_test_data)

accuracy_on_test_data

input_mail=["URGENT! You have won a 1 week FREE membership in our £100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net LCCLTD POBOX 4403LDNW1A7RW18"]
input_data_features=feature_extraction.transform(input_mail)
prediction=model.predict(input_data_features)
if prediction==0:
  print("SPAM MAIL")
else:
  print("HAM MAIL")